debug: false

logging:
  level:
    uno.fastcampus.testdata: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.test.context.transaction.TransactionContext: debug

spring:
  application.name: test-data
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always
  security.oauth2.client:
    registration:
      github:
        client-id: ${GITHUB_OAUTH_CLIENT_ID}
        client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always